/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/map.glb -o src/components/Map.jsx -r public -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/map.glb')
  return (
    <group {...props} dispose={null}>
      <group name="Plane" scale={19.939}>
        <mesh name="Plane_1" geometry={nodes.Plane_1.geometry} material={materials.DarkGrey} />
        <mesh name="Plane_2" geometry={nodes.Plane_2.geometry} material={nodes.Plane_2.material} />
        <mesh name="Plane_3" geometry={nodes.Plane_3.geometry} material={materials.Grey} />
      </group>
      <group name="Barrier_Fixed" position={[-16.145, 0, -11.357]} scale={[0.738, 0.365, 0.365]}>
        <mesh name="Cube008" geometry={nodes.Cube008.geometry} material={materials.Grey} />
        <mesh name="Cube008_1" geometry={nodes.Cube008_1.geometry} material={materials.DarkGrey} />
        <mesh name="Cube008_2" geometry={nodes.Cube008_2.geometry} material={materials.Yellow} />
        <mesh name="Cube008_3" geometry={nodes.Cube008_3.geometry} material={materials.White} />
        <mesh name="Cube008_4" geometry={nodes.Cube008_4.geometry} material={materials.Texture_Fence} />
        <mesh name="Cube008_5" geometry={nodes.Cube008_5.geometry} material={materials.Red} />
        <mesh name="Cube008_6" geometry={nodes.Cube008_6.geometry} material={materials.Wood} />
      </group>
      <group name="Barrier_Large" position={[1.739, 0, 8.084]} scale={[0.738, 0.365, 0.365]}>
        <mesh name="Cube029" geometry={nodes.Cube029.geometry} material={materials.Grey} />
        <mesh name="Cube029_1" geometry={nodes.Cube029_1.geometry} material={materials.DarkGrey} />
        <mesh name="Cube029_2" geometry={nodes.Cube029_2.geometry} material={materials.Yellow} />
        <mesh name="Cube029_3" geometry={nodes.Cube029_3.geometry} material={materials.White} />
        <mesh name="Cube029_4" geometry={nodes.Cube029_4.geometry} material={materials.Texture_Fence} />
      </group>
      <group name="Barrier_Single" position={[-5.006, 0, 8.345]} scale={[0.738, 0.365, 0.365]}>
        <mesh name="Cube046" geometry={nodes.Cube046.geometry} material={materials.Grey} />
        <mesh name="Cube046_1" geometry={nodes.Cube046_1.geometry} material={materials.DarkGrey} />
        <mesh name="Cube046_2" geometry={nodes.Cube046_2.geometry} material={materials.Yellow} />
        <mesh name="Cube046_3" geometry={nodes.Cube046_3.geometry} material={materials.White} />
      </group>
      <group name="Barrier_Trash" position={[-3.275, 0, -7.475]} rotation={[Math.PI / 2, 0, 0.536]} scale={0.588}>
        <mesh name="Cube040" geometry={nodes.Cube040.geometry} material={materials.Wood} />
        <mesh name="Cube040_1" geometry={nodes.Cube040_1.geometry} material={materials.Wood_Light} />
        <mesh name="Cube040_2" geometry={nodes.Cube040_2.geometry} material={materials.Sack} />
        <mesh name="Cube040_3" geometry={nodes.Cube040_3.geometry} material={materials.Black} />
        <mesh name="Cube040_4" geometry={nodes.Cube040_4.geometry} material={materials.Grey} />
        <mesh name="Cube040_5" geometry={nodes.Cube040_5.geometry} material={materials.Red} />
      </group>
      <mesh name="BearTrap_Closed" geometry={nodes.BearTrap_Closed.geometry} material={materials.Grey} position={[4.758, 0, 17.858]} scale={0.586} />
      <mesh name="BearTrap_Open" geometry={nodes.BearTrap_Open.geometry} material={materials.Grey} position={[7.055, 0, 18.303]} scale={0.586} />
      <mesh name="BrickWall_2" geometry={nodes.BrickWall_2.geometry} material={materials.Brick} position={[-12.643, 0, -19.511]} scale={[0.216, 0.082, 0.216]} />
      <group name="CardboardBoxes_1" position={[-17.566, 0, -16.401]} scale={0.363}>
        <mesh name="Cube056" geometry={nodes.Cube056.geometry} material={materials.Cardboard} />
        <mesh name="Cube056_1" geometry={nodes.Cube056_1.geometry} material={materials.Tape} />
      </group>
      <group name="CardboardBoxes_2" position={[6.103, 0, -0.501]} scale={[0.363, 0.363, 0.465]}>
        <mesh name="Cube059" geometry={nodes.Cube059.geometry} material={materials.Blue} />
        <mesh name="Cube059_1" geometry={nodes.Cube059_1.geometry} material={materials.Tape} />
      </group>
      <group name="CardboardBoxes_3" position={[-4.327, 0, 5.375]} scale={0.363}>
        <mesh name="Cube063" geometry={nodes.Cube063.geometry} material={materials.Cardboard} />
        <mesh name="Cube063_1" geometry={nodes.Cube063_1.geometry} material={materials.Tape} />
      </group>
      <group name="CardboardBoxes_4" position={[-10.203, 0, 16.579]} rotation={[0, 0, -Math.PI / 2]} scale={0.363}>
        <mesh name="Cube054" geometry={nodes.Cube054.geometry} material={materials.Cardboard} />
        <mesh name="Cube054_1" geometry={nodes.Cube054_1.geometry} material={materials.Tape} />
      </group>
      <group name="Container_Long" position={[5.132, 0, -8.474]} scale={0.586}>
        <mesh name="Cube012" geometry={nodes.Cube012.geometry} material={materials.Red} />
        <mesh name="Cube012_1" geometry={nodes.Cube012_1.geometry} material={materials.Grey} />
      </group>
      <group name="Container_Small" position={[-1.334, 0, 11.969]} rotation={[0, 0.505, 0]} scale={0.586}>
        <mesh name="Cube269" geometry={nodes.Cube269.geometry} material={materials.Blue} />
        <mesh name="Cube269_1" geometry={nodes.Cube269_1.geometry} material={materials.Grey} />
      </group>
      <group name="Crate" position={[-14.901, 0, -17.461]} scale={0.391}>
        <mesh name="Cube038" geometry={nodes.Cube038.geometry} material={materials.Wood} />
        <mesh name="Cube038_1" geometry={nodes.Cube038_1.geometry} material={materials.Wood_Light} />
      </group>
      <group name="Debris_BrokenCar" position={[10.405, 0, 17.134]} rotation={[0, 1.165, 0]} scale={1.493}>
        <mesh name="Cube034" geometry={nodes.Cube034.geometry} material={materials.Rust} />
        <mesh name="Cube034_1" geometry={nodes.Cube034_1.geometry} material={materials.Black} />
        <mesh name="Cube034_2" geometry={nodes.Cube034_2.geometry} material={materials.Grey} />
        <mesh name="Cube034_3" geometry={nodes.Cube034_3.geometry} material={materials.Rust} />
      </group>
      <mesh name="Debris_Papers_1" geometry={nodes.Debris_Papers_1.geometry} material={materials.White} position={[6.242, 0, -6.59]} rotation={[0, 0.308, 0]} scale={0.114} />
      <mesh name="Debris_Papers_2" geometry={nodes.Debris_Papers_2.geometry} material={materials.White} position={[-0.787, 0, -3.716]} rotation={[0, 0.308, 0]} scale={0.114} />
      <mesh name="Debris_Papers_3" geometry={nodes.Debris_Papers_3.geometry} material={materials.White} position={[1.336, 0, -4.009]} rotation={[0, 0.308, 0]} scale={0.114} />
      <mesh name="Debris_Tires" geometry={nodes.Debris_Tires.geometry} material={materials.Black} position={[5.24, 0, 16.483]} scale={0.586} />
      <group name="ExplodingBarrel" position={[17.382, 0, 17.093]} scale={0.365}>
        <mesh name="Cylinder003" geometry={nodes.Cylinder003.geometry} material={materials.Red} />
        <mesh name="Cylinder003_1" geometry={nodes.Cylinder003_1.geometry} material={materials.Grey} />
        <mesh name="Cylinder003_2" geometry={nodes.Cylinder003_2.geometry} material={materials.White} />
      </group>
      <group name="ExplodingBarrel_Spilled" position={[16.67, 0, 13.345]} rotation={[0, 0, -1.565]} scale={0.365}>
        <mesh name="Cylinder005" geometry={nodes.Cylinder005.geometry} material={materials.Red} />
        <mesh name="Cylinder005_1" geometry={nodes.Cylinder005_1.geometry} material={materials.Grey} />
        <mesh name="Cylinder005_2" geometry={nodes.Cylinder005_2.geometry} material={materials.Oil} />
        <mesh name="Cylinder005_3" geometry={nodes.Cylinder005_3.geometry} material={materials.White} />
      </group>
      <group name="GasCan" position={[-16.455, 0, -17.314]} rotation={[0, -0.573, 0]} scale={0.844}>
        <mesh name="Cube018" geometry={nodes.Cube018.geometry} material={materials.Red} />
        <mesh name="Cube018_1" geometry={nodes.Cube018_1.geometry} material={materials.DarkRed} />
        <mesh name="Cube018_2" geometry={nodes.Cube018_2.geometry} material={materials.Black} />
      </group>
      <group name="GasTank" position={[10.496, 0, -11.276]} scale={[0.483, 0.403, 0.483]}>
        <mesh name="Cylinder004" geometry={nodes.Cylinder004.geometry} material={materials.Yellow} />
        <mesh name="Cylinder004_1" geometry={nodes.Cylinder004_1.geometry} material={materials.Grey} />
        <mesh name="Cylinder004_2" geometry={nodes.Cylinder004_2.geometry} material={materials.Wood} />
      </group>
      <group name="Health" position={[-13.537, 0, -18.814]} rotation={[0, 0.635, 0]} scale={1.096}>
        <mesh name="Cube007" geometry={nodes.Cube007.geometry} material={materials.Green} />
        <mesh name="Cube007_1" geometry={nodes.Cube007_1.geometry} material={materials.Wood} />
        <mesh name="Cube007_2" geometry={nodes.Cube007_2.geometry} material={materials.DarkGreen} />
      </group>
      <group name="Landmine" position={[9.097, 0, 1.629]} scale={[0.393, 0.118, 0.393]}>
        <mesh name="Cylinder029" geometry={nodes.Cylinder029.geometry} material={materials.DarkGrey} />
        <mesh name="Cylinder029_1" geometry={nodes.Cylinder029_1.geometry} material={materials.Red} />
        <mesh name="Cylinder029_2" geometry={nodes.Cylinder029_2.geometry} material={materials.Grey} />
      </group>
      <group name="MetalFence" position={[-17.322, 0, 8.346]} scale={0.104}>
        <mesh name="Cylinder020" geometry={nodes.Cylinder020.geometry} material={materials.Grey} />
        <mesh name="Cylinder020_1" geometry={nodes.Cylinder020_1.geometry} material={materials.Texture_Fence} />
      </group>
      <mesh name="Pallet" geometry={nodes.Pallet.geometry} material={materials.Wood} position={[15.99, 0, 18.377]} scale={[0.093, 0.096, 0.889]} />
      <group name="Pallet_Broken" position={[-15.053, 0, -18.73]} scale={0.586}>
        <mesh name="Cube009" geometry={nodes.Cube009.geometry} material={materials.Wood} />
        <mesh name="Cube009_1" geometry={nodes.Cube009_1.geometry} material={materials.Wood_Light} />
      </group>
      <group name="Pipes" position={[4.113, 0, 12.113]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={0.88}>
        <mesh name="Cylinder024" geometry={nodes.Cylinder024.geometry} material={materials.Grey} />
        <mesh name="Cylinder024_1" geometry={nodes.Cylinder024_1.geometry} material={materials.Grey2} />
      </group>
      <mesh name="SackTrench" geometry={nodes.SackTrench.geometry} material={materials.Sack} position={[-16.488, 0, -0.046]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.586} />
      <mesh name="SackTrench_Small" geometry={nodes.SackTrench_Small.geometry} material={materials.Sack} position={[-5.283, 0, 0.911]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.586} />
      <group name="Sign" position={[-15.389, 0, -16.22]} rotation={[0, 0.308, 0]} scale={[0.285, 0.285, 0.024]}>
        <mesh name="Cube014" geometry={nodes.Cube014.geometry} material={materials.Yellow} />
        <mesh name="Cube014_1" geometry={nodes.Cube014_1.geometry} material={materials.Brown} />
      </group>
      <mesh name="Sofa" geometry={nodes.Sofa.geometry} material={materials.Red} position={[-7.975, 0, -18.421]} rotation={[0, -0.009, 0]} scale={1.398} />
      <mesh name="Sofa_Small" geometry={nodes.Sofa_Small.geometry} material={materials.Red} position={[18.288, 0, 15.43]} rotation={[Math.PI, -1.078, Math.PI]} scale={1.398} />
      <group name="StreetLight" position={[-14.621, 0, -8.927]} scale={0.586}>
        <mesh name="Cylinder023" geometry={nodes.Cylinder023.geometry} material={materials.Grey} />
        <mesh name="Cylinder023_1" geometry={nodes.Cylinder023_1.geometry} material={materials.Light} />
      </group>
      <group name="Structure_1" position={[-9.838, 0, 8.517]} scale={0.897}>
        <mesh name="Cube035" geometry={nodes.Cube035.geometry} material={materials.Red} />
        <mesh name="Cube035_1" geometry={nodes.Cube035_1.geometry} material={materials.Cardboard} />
        <mesh name="Cube035_2" geometry={nodes.Cube035_2.geometry} material={materials.Tape} />
        <mesh name="Cube035_3" geometry={nodes.Cube035_3.geometry} material={materials.Wood} />
        <mesh name="Cube035_4" geometry={nodes.Cube035_4.geometry} material={materials.Grey} />
        <mesh name="Cube035_5" geometry={nodes.Cube035_5.geometry} material={materials.Grey2} />
      </group>
      <group name="Structure_2" position={[12.867, 0, -17.427]} scale={0.586}>
        <mesh name="Cube329" geometry={nodes.Cube329.geometry} material={materials.Green} />
        <mesh name="Cube329_1" geometry={nodes.Cube329_1.geometry} material={materials.Yellow} />
        <mesh name="Cube329_2" geometry={nodes.Cube329_2.geometry} material={materials.Cardboard} />
        <mesh name="Cube329_3" geometry={nodes.Cube329_3.geometry} material={materials.Tape} />
        <mesh name="Cube329_4" geometry={nodes.Cube329_4.geometry} material={materials.Wood} />
        <mesh name="Cube329_5" geometry={nodes.Cube329_5.geometry} material={materials.Grey} />
        <mesh name="Cube329_6" geometry={nodes.Cube329_6.geometry} material={materials.Grey2} />
        <mesh name="Cube329_7" geometry={nodes.Cube329_7.geometry} material={materials.Wood_Light} />
      </group>
      <group name="Structure_3" position={[-9.201, 0, -12.116]} scale={0.897}>
        <mesh name="Cube333" geometry={nodes.Cube333.geometry} material={materials.Cardboard} />
        <mesh name="Cube333_1" geometry={nodes.Cube333_1.geometry} material={materials.Tape} />
        <mesh name="Cube333_2" geometry={nodes.Cube333_2.geometry} material={materials.Wood} />
        <mesh name="Cube333_3" geometry={nodes.Cube333_3.geometry} material={materials.Grey} />
        <mesh name="Cube333_4" geometry={nodes.Cube333_4.geometry} material={materials.Grey2} />
        <mesh name="Cube333_5" geometry={nodes.Cube333_5.geometry} material={materials.Blue} />
      </group>
      <group name="Structure_4" position={[8.973, 0, 7.105]} scale={0.586}>
        <mesh name="Cube339" geometry={nodes.Cube339.geometry} material={materials.Cyan} />
        <mesh name="Cube339_1" geometry={nodes.Cube339_1.geometry} material={materials.Yellow} />
        <mesh name="Cube339_2" geometry={nodes.Cube339_2.geometry} material={materials.Wood} />
        <mesh name="Cube339_3" geometry={nodes.Cube339_3.geometry} material={materials.Grey} />
        <mesh name="Cube339_4" geometry={nodes.Cube339_4.geometry} material={materials.Green} />
        <mesh name="Cube339_5" geometry={nodes.Cube339_5.geometry} material={materials.Black} />
        <mesh name="Cube339_6" geometry={nodes.Cube339_6.geometry} material={materials.DarkGrey} />
      </group>
      <group name="Tank" position={[11.299, 0, -3.481]} rotation={[0, -0.769, 0]} scale={1.123}>
        <mesh name="Cylinder010" geometry={nodes.Cylinder010.geometry} material={materials.Grey} />
        <mesh name="Cylinder010_1" geometry={nodes.Cylinder010_1.geometry} material={materials.Tank_Main} />
        <mesh name="Cylinder010_2" geometry={nodes.Cylinder010_2.geometry} material={materials.Tank_Main} />
        <mesh name="Cylinder010_3" geometry={nodes.Cylinder010_3.geometry} material={materials.Black} />
      </group>
      <group name="TrafficCone" position={[-18.912, 0, -11.341]} scale={0.233}>
        <mesh name="Cylinder001" geometry={nodes.Cylinder001.geometry} material={materials.Orange} />
        <mesh name="Cylinder001_1" geometry={nodes.Cylinder001_1.geometry} material={materials.Wood} />
      </group>
      <group name="TrashContainer" position={[18.787, 0, -8.575]} rotation={[Math.PI, -1.563, Math.PI]} scale={0.586}>
        <mesh name="Cube053" geometry={nodes.Cube053.geometry} material={materials.Green} />
        <mesh name="Cube053_1" geometry={nodes.Cube053_1.geometry} material={materials.DarkGrey} />
        <mesh name="Cube053_2" geometry={nodes.Cube053_2.geometry} material={materials.Grey} />
      </group>
      <group name="TrashContainer_Open" position={[-17.727, 0, -18.786]} scale={0.586}>
        <mesh name="Cube017" geometry={nodes.Cube017.geometry} material={materials.Green} />
        <mesh name="Cube017_1" geometry={nodes.Cube017_1.geometry} material={materials.DarkGrey} />
        <mesh name="Cube017_2" geometry={nodes.Cube017_2.geometry} material={materials.Grey} />
        <mesh name="Cube017_3" geometry={nodes.Cube017_3.geometry} material={materials.Black} />
        <mesh name="Cube017_4" geometry={nodes.Cube017_4.geometry} material={materials.Oil} />
      </group>
      <group name="Tree_1" position={[-13.402, 0, 2.669]} scale={0.796}>
        <mesh name="Cube314" geometry={nodes.Cube314.geometry} material={materials.Tree_Wood} />
        <mesh name="Cube314_1" geometry={nodes.Cube314_1.geometry} material={materials.Tree_Green} />
      </group>
      <group name="Tree_2" position={[17.154, 0, 1.184]} scale={0.704}>
        <mesh name="Cube044" geometry={nodes.Cube044.geometry} material={materials.Tree_Wood} />
        <mesh name="Cube044_1" geometry={nodes.Cube044_1.geometry} material={materials.Tree_Green} />
      </group>
      <group name="Tree_3" position={[-4.936, 0, 15.833]} rotation={[0, 0.27, 0]} scale={0.704}>
        <mesh name="Mesh001" geometry={nodes.Mesh001.geometry} material={materials.Tree_Green} />
        <mesh name="Mesh001_1" geometry={nodes.Mesh001_1.geometry} material={materials.Tree_Wood} />
      </group>
      <group name="Tree_4" position={[-7.547, 0, -3.864]} rotation={[0, -0.709, 0]} scale={0.422}>
        <mesh name="Cube041" geometry={nodes.Cube041.geometry} material={materials.Tree_Wood} />
        <mesh name="Cube041_1" geometry={nodes.Cube041_1.geometry} material={materials.Tree_Green} />
      </group>
      <group name="WaterTank_Floor" position={[-15.67, 0, 14.914]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={0.88}>
        <mesh name="Cylinder015" geometry={nodes.Cylinder015.geometry} material={materials.Grey} />
        <mesh name="Cylinder015_1" geometry={nodes.Cylinder015_1.geometry} material={materials.Grey2} />
        <mesh name="Cylinder015_2" geometry={nodes.Cylinder015_2.geometry} material={materials.White} />
      </group>
      <group name="WaterTank_Platform" position={[5.58, 0, -15.05]} scale={0.586}>
        <mesh name="Cylinder030" geometry={nodes.Cylinder030.geometry} material={materials.Grey} />
        <mesh name="Cylinder030_1" geometry={nodes.Cylinder030_1.geometry} material={materials.Grey2} />
        <mesh name="Cylinder030_2" geometry={nodes.Cylinder030_2.geometry} material={materials.White} />
      </group>
      <group name="WoodPlanks" position={[18.305, 0, 18.356]} scale={0.586}>
        <mesh name="Cube002" geometry={nodes.Cube002.geometry} material={materials.Wood} />
        <mesh name="Cube002_1" geometry={nodes.Cube002_1.geometry} material={materials.Wood_Light} />
      </group>
      <group name="TrashContainer_Open001" position={[-17.727, 0, -18.786]} scale={0.586}>
        <mesh name="Cube003" geometry={nodes.Cube003.geometry} material={materials.Green} />
        <mesh name="Cube003_1" geometry={nodes.Cube003_1.geometry} material={materials.DarkGrey} />
        <mesh name="Cube003_2" geometry={nodes.Cube003_2.geometry} material={materials.Grey} />
        <mesh name="Cube003_3" geometry={nodes.Cube003_3.geometry} material={materials.Black} />
        <mesh name="Cube003_4" geometry={nodes.Cube003_4.geometry} material={materials.Oil} />
      </group>
      <group name="CardboardBoxes_2001" position={[5.654, 0, 0.486]} rotation={[0, -0.116, 0]} scale={[0.363, 0.363, 0.465]}>
        <mesh name="Cube004" geometry={nodes.Cube004.geometry} material={materials.Blue} />
        <mesh name="Cube004_1" geometry={nodes.Cube004_1.geometry} material={materials.Tape} />
      </group>
      <group name="CardboardBoxes_2002" position={[6.821, 0, 0.509]} scale={[0.363, 0.363, 0.465]}>
        <mesh name="Cube005" geometry={nodes.Cube005.geometry} material={materials.Blue} />
        <mesh name="Cube005_1" geometry={nodes.Cube005_1.geometry} material={materials.Tape} />
      </group>
      <group name="CardboardBoxes_2003" position={[6.156, 0.925, -0.009]} rotation={[0, 0.196, 0]} scale={[0.363, 0.363, 0.465]}>
        <mesh name="Cube010" geometry={nodes.Cube010.geometry} material={materials.Blue} />
        <mesh name="Cube010_1" geometry={nodes.Cube010_1.geometry} material={materials.Tape} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/map.glb')
